while not Exception:
    print("Test")
    Exception
